storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

dataset:
 value: mnist
 version: '1.0.0'
 workspace: 'kuberlab-demo'
 wizard:
   name: "Mnist dataset configuration"
   kind: dataset

src:
  value: https://github.com/kuberlab/spark-bigdl-examples
  wizard:
    name: "Source Code"
    kind: git

spark_type:
  value: "cluster"
  wizard:
    name: "Local or Cluster spark mode"
    kind: select
    options:
    - "cluster"
    - "local"
